- name: Install maven
  ansible.builtin.import_role:
    name: common
    tasks_from: install-maven
- name: App set up
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup
- name: configure application
  ansible.builtin.import_role:
   name: common
   tasks_from: configure-maven
- name: service configure
  ansible.builtin.import_role:
    name: common
    tasks_from: service-configure
- name: Installing mysql
  ansible.builtin.package:
    name: mysql
    state: installed
- name: Copying schema directory to /app
  ansible.builtin.copy:
    src: "{{DIRECTORY}}/schema"
    dest: /app
- name: Loading schema
  ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -pRoboShop@1 < /app/schema/shipping.sql"
  notify:
    name: restart-shipping






