     - name: Creating roboshop user
       ansible.builtin.user:
        name: roboshop
        create_home: yes
     - name: Creating /app directory
       ansible.builtin.file:
        path: /app
        state: directory
     - name: "Download {{COMPONENT}} code"
       ansible.builtin.get_url:
        url: "https://roboshop-builds.s3.amazonaws.com/{{COMPONENT}}.zip"
        dest: /tmp
     - name: "Unzipping "{{COMPONENT}} code"
       ansible.builtin.unarchive:
        src: "/tmp/{{COMPONENT}}.zip"
        dest: /app
        remote_src: yes
