- name: "Copying {{COMPONENT}}.repo file"
  ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
- name: Installing mongodb-org-shell
  ansible.builtin.package:
     name: mongodb-org-shell
     state: present
- name: Loading schema
  ansible.builtin.shell: "mongo --host {{MONDODB_HOST}} </app/schema/{{COMPONENT}}.js"
