- name: Disabling current mysql repo
  ansible.builtin.shell: dnf module disable mysql -y
- name: copying mysql. repo file
  ansible.builtin.copy:
    src: /root/ansible-robo/mysql.repo
    dest: /etc/yum.repos.d/mysql.repo
- name: Installing mysql server
  ansible.builtin.package:
    name: mysql-community-server
    state: installed
